### ISSUE TITLE
Review Pyup PR #168

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#167]
Pyup submitted its first PR to the repo. Review it to make sure tests run (at the least) before merging.

**Comment by alison985** [comment]
Learned it closes a days PR if not handled that day so this went from #161 to #168.

**Comment by alison985** [comment]
Got this test failure: ======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'SSL_ST_INIT')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/app/tests/__init__.py", line 17, in <module>
    from redash import create_app
  File "/app/redash/__init__.py", line 69, in <module>
    import_query_runners(settings.QUERY_RUNNERS)
  File "/app/redash/query_runner/__init__.py", line 199, in import_query_runners
    __import__(runner_import)
  File "/app/redash/query_runner/big_query.py", line 18, in <module>
    import apiclient.errors
  File "/usr/local/lib/python2.7/dist-packages/apiclient/__init__.py", line 19, in <module>
    from googleapiclient import discovery
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery.py", line 71, in <module>
    from oauth2client.client import GoogleCredentials
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/client.py", line 47, in <module>
    from oauth2client import crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/crypt.py", line 45, in <module>
    from oauth2client import _openssl_crypt
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_openssl_crypt.py", line 16, in <module>
    from OpenSSL import crypto
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by alison985** [comment]
Needed to upgrade pyOpenSSL==16.2.0 in python requirements file.

**Comment by alison985** [comment]
Victor, there is no specific test for this. Any issues would be caught in the regression.
