### ISSUE TITLE
kombu async error

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#403]
When starting up my environment I get this error that shuts down the worker_1 box.

worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/bin/celery", line 11, in <module>
worker_1    |     sys.exit(main())
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 14, in main
worker_1    |     _main()
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 326, in main
worker_1    |     cmd.execute_from_commandline(argv)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in execute_from_commandline
worker_1    |     super(CeleryCommand, self).execute_from_commandline(argv)))
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 281, in execute_from_commandline
worker_1    |     return self.handle_argv(self.prog_name, argv[1:])
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 480, in handle_argv
worker_1    |     return self.execute(command, argv)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 412, in execute
worker_1    |     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/worker.py", line 221, in run_from_argv
worker_1    |     return self(*args, **options)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 244, in __call__
worker_1    |     ret = self.run(*args, **kwargs)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/worker.py", line 255, in run
worker_1    |     **kwargs)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/worker/worker.py", line 99, in __init__
worker_1    |     self.setup_instance(**self.prepare_args(**kwargs))
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/worker/worker.py", line 122, in setup_instance
worker_1    |     self.should_use_eventloop() if use_eventloop is None
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/worker/worker.py", line 241, in should_use_eventloop
worker_1    |     self._conninfo.transport.implements.async and
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/kombu/transport/base.py", line 125, in __getattr__
worker_1    |     raise AttributeError(key)
worker_1    | AttributeError: async

**Comment by alison985** [comment]
This appears to be a new error that is discussed in this SO page: https://stackoverflow.com/questions/50460254/airflow-worker-breaking-due-to-update-in-kombu-async-error#_=_

I'm upping the celery version to compensate.

**Comment by alison985** [comment]
PR #405
