### ISSUE TITLE
missing extensions folder when npm run build

### ISSUE THREAD

**Issue by alison985** [mozilla/redash#596]
### Issue Summary

I have to make the /client/app/extensions directory to get `npm run build` to work.

### Steps to Reproduce

When I 
1) make a new branch from getredash master and 
2) try to run `npm run build` 

I get the following output

```
(getredash) Alisons-MacBook-Air:stanton_ventures_redash alison$ npm run build

> redash-client@5.0.0 build /Users/alison/Sites/stanton_ventures_redash
> rm -rf ./client/dist/ && NODE_ENV=production webpack

fs.js:1659
      binding.lstat(baseLong);
              ^

Error: ENOENT: no such file or directory, lstat '/Users/alison/Sites/stanton_ventures_redash/client/app/extensions'
    at Object.realpathSync (fs.js:1659:15)
    at Object.<anonymous> (/Users/alison/Sites/stanton_ventures_redash/webpack.config.js:22:26)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at requireConfig (/Users/alison/Sites/stanton_ventures_redash/node_modules/webpack/bin/convert-argv.js:97:18)
    at /Users/alison/Sites/stanton_ventures_redash/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (native)
    at module.exports (/Users/alison/Sites/stanton_ventures_redash/node_modules/webpack/bin/convert-argv.js:102:15)
    at yargs.parse (/Users/alison/Sites/stanton_ventures_redash/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/Users/alison/Sites/stanton_ventures_redash/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/Users/alison/Sites/stanton_ventures_redash/node_modules/webpack/bin/webpack.js:152:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redash-client@5.0.0 build: `rm -rf ./client/dist/ && NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redash-client@5.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alison/.npm/_logs/2018-10-14T22_56_55_543Z-debug.log
```

I consider this a bug because I should be able to run the `npm run build` command and have it succeed.

To get it to work I had to manually create the /client/app/extensions/ directory.

### Technical details:

* Redash Version: latest - 5.0.1
* Browser/OS: Mac and Firefox
* How did you install Redash: docker development instructions

FYI @emtwo

**Comment by emtwo** [comment]
@alison985 Unfortunately this is a bit confusing but it is actually by design because now `make build` needs to be called instead of `npm run build`.

`make build` will create the extensions directory and then do `npm run build` as well.

We do need to work on a better way in general improving the build process so that `npm run build` can happen in the container instead of the host.

**Comment by emtwo** [comment]
@alison985 In the interim, there was a solution upstream just doing what you described, having an extensions directory by default: https://github.com/getredash/redash/pull/2952
