### ISSUE TITLE
TypeError: sequence index must be integer, not 'str'

### ISSUE THREAD

**Issue by robotblake** [mozilla/redash#63]
https://sentry.prod.mozaws.net/operations/pipeline-sql-prod/issues/383536/

```
TypeError: sequence index must be integer, not 'str'
(2 additional frame(s) were not displayed)
...
  File "flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "redash/authentication/google_oauth.py", line 97, in authorized
    access_token = resp['access_token']

Exception on /oauth/google_callback [GET]
```

**Comment by robotblake** [comment]
This is sometimes causing issues with logging in and can cause an infinite loop which may or may not be fixed by a clean profile / wiping cookies.

It appears that a relevant issue is here: https://github.com/lepture/example-oauth2-server/issues/24. The exception we're getting isn't super useful so I'm wondering if upgrading flask-oauthlib to include the fix from https://github.com/lepture/flask-oauthlib/pull/223 would help figure out what's going on.

**Comment by rafrombrc** [comment]
This is very hard to reliably reproduce, but we think upgrading the flask-oauthlib may resolve it so we're going to start there.

**Comment by rafrombrc** [comment]
We think this is resolved, closing for now, will reopen if the issue turns up again.

**Comment by crooy** [comment]
we appear to be experiencing this bug:

```
[2017-12-11 08:33:44,374] ERROR in app: Exception on /oauth/google_callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/redash/redash.3.0.0.b3134/redash/authentication/google_oauth.py", line 97, in authorized
    access_token = resp['access_token']
TypeError: sequence index must be integer, not 'str'
[2017-12-11 08:33:44,374][PID:19908][ERROR][redash] Exception on /oauth/google_callback [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/redash/redash.3.0.0.b3134/redash/authentication/google_oauth.py", line 97, in authorized
    access_token = resp['access_token']
TypeError: sequence index must be integer, not 'str'
```

**Comment by crooy** [comment]
oh wait this is not the main redash repo.. sorry.. still you might have this issue too ;-)
