### ISSUE TITLE
Python exception on some BigQuery comment lines

### ISSUE THREAD

**Issue by washort** [mozilla/redash#987]
Executing
```
-- */
SELECT 1
```

yields this traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/redash/worker.py", line 88, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/redash/tasks/queries.py", line 717, in execute_query
    scheduled_query).run()
  File "/app/redash/tasks/queries.py", line 663, in run
    raise result
QueryExecutionError: descriptor 'strip' requires a 'str' object but received a 'unicode'
```

**Comment by jezdez** [comment]
Woah, weird!

**Comment by jezdez** [comment]
@washort Mind a quick review of https://github.com/mozilla/redash-stmo/pull/58?
