### ISSUE TITLE
BigQuery Data Source `Error running query: Expecting ‘:’ delimiter: line 5106 column 35 (char 219544)`

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/redash#993]
### Issue Summary
Users reported the following issue when running queries against a data source 'Telemetry - (BigQuery)'
```
Error running query: Expecting ‘:’ delimiter: line 5106 column 35 (char 219544)
```

Traceback:
`
Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task R = retval = fun(*args, **kwargs) File "/app/redash/worker.py", line 88, in __call__ return TaskBase.__call__(self, *args, **kwargs) File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 648, in __protected_call__ return self.run(*args, **kwargs) File "/app/redash/tasks/queries.py", line 717, in execute_query scheduled_query).run() File "/app/redash/tasks/queries.py", line 663, in run raise result QueryExecutionError: Expecting ':' delimiter: line 5106 column 35 (char 219544)
`

Looking at the [logs](https://console.cloud.google.com/logs/viewer?interval=PT6H&project=moz-fx-data-stmo-prod-33f2&organizationId=442341870013&minLogLevel=0&expandAll=false&timestamp=2019-11-18T17%3A56%3A15.470000000Z&customFacets&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22us-west1%22%0Aresource.labels.project_id%3D%22moz-fx-data-stmo-prod-33f2%22%0Aresource.labels.pod_name%3D%22stmo-prod-stmo-app-1-worker-adhoc-bq-68756bdccf-g78kj%22%0Aresource.labels.cluster_name%3D%22stmo-prod-v1%22%0Aresource.labels.container_name%3D%22stmo-prod-stmo-app-1-worker-adhoc-bq%22%0Aresource.labels.namespace_name%3D%22prod-stmo%22%0Atimestamp%3D%222019-11-18T16%3A29%3A00.032627405Z%22%0AinsertId%3D%22chmsqpwm7cowmszbx%22&scrollTimestamp=2019-11-18T16%3A29%3A00.377837575Z&dateRangeStart=2019-11-18T12%3A05%3A17.631Z&dateRangeEnd=2019-11-18T18%3A05%3A17.631Z) I see several `Refreshing access_token` entries before the errors actually started to occur.

`
Traceback (most recent call last): File "/app/redash/tasks/queries.py", line 642, in run data, error = query_runner.run_query(annotated_query, self.user) File "/usr/local/lib/python2.7/site-packages/redash_stmo/query_runner/big_query.py", line 90, in run_query return super(BigQuery, self).run_query(query, user) File "/app/redash/query_runner/big_query.py", line 408, in run_query bigquery_service = self._get_bigquery_service() File "/app/redash/query_runner/big_query.py", line 164, in _get_bigquery_service return build("bigquery", "v2", http=http) File "/usr/local/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper return wrapped(*args, **kwargs) File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 210, in build credentials=credentials) File "/usr/local/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper return wrapped(*args, **kwargs) File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 317, in build_from_document service = json.loads(service) File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads return _default_decoder.decode(s) File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/local/lib/python2.7/json/decoder.py", line 380, in raw_decode obj, end = self.scan_once(s, idx) ValueError: Expecting ':' delimiter: line 5106 column 35 (char 219544)
`

Restarting the celery worker associated with this data source resolved the issue.

**Comment by jezdez** [comment]
Hm, we should look into if this is still the case.
